# Generated by Django 2.1.5 on 2019-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190410_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
