# Generated by Django 2.1.5 on 2019-04-25 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190425_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
