# Generated by Django 2.1.5 on 2019-04-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190425_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user1',
            new_name='user',
        ),
    ]
