# Generated by Django 2.1.5 on 2019-04-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190427_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
