# Generated by Django 2.1.5 on 2019-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='x',
            field=models.BooleanField(default=True),
        ),
    ]
